version: 2
updates:
  - package-ecosystem: pip
    directory: /provisioning/
    schedule:
      interval: daily
    labels:
      - pip
      - dependencies
    groups:
      k8s:
        patterns:
          - "kubernetes"
        update-types:
          - "minor"
          - "patch"
      ansible:
        patterns:
          - "ansible"
        update-types:
          - "major"
          - "minor"
          - "patch"
