vm:
  network:
    cidr: "10.10.0.10/32"
  cluster:
    controlplane:
      box: bento/ubuntu-22.04
      cpu: 2
      memory: 2048
    node:
      count: 2
      box: bento/ubuntu-22.04
      cpu: 1
      memory: 2048
k8s:
  version: 1.29
  calico:
    version: 3.28.0
  dashboard:
    version: 2.7.0
    # enable: true
  network:
    pod_cidr: 172.16.1.0/16
    service_cidr: 172.17.1.0/18
