vm:
  controlplane:
    box: generic/ubuntu2204
    cpu: 2
    memory: 2048
  node:
    count: 2
    box: generic/ubuntu2204
    cpu: 1
    memory: 2048
k8s:
  version: 1.29
  calico:
    version: 3.27.3
  dashboard:
    version: 2.7.0
    # enable: true
  network:
    pod_cidr: 172.16.1.0/16
    service_cidr: 172.17.1.0/18
