# reference: https://github.com/cri-o/packaging

- name: Add cri-o apt key
  become: true
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/Release.key
    dest: /etc/apt/trusted.gpg.d/cri-o-apt-keyring.asc
    checksum: sha256:5fe267a9ae47ffd566624057f2c8f64ab8a786a9c650e92cc22135381b04f12b

- name: Add cri-o apt source
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/cri-o-apt-keyring.asc] https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/ /"
    state: present
    update_cache: yes

- name: Install cri-o binaries
  become: true
  ansible.builtin.apt:
    name: cri-o
    state: present

# sudo systemctl enable --now cri-o
- name: Enable the cri-o service
  become: true
  ansible.builtin.systemd_service:
    name: cri-o
    state: started
    enabled: true
    masked: false
