- name: Create kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: Copy kube config
  become: true
  ansible.builtin.copy:
    src: "{{ kubeadmin_config }}"
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    remote_src: true
    force: true

- name: Create vagrant k8s directory
  file:
    path: "/vagrant/.vagrant/k8s"
    state: directory

- name: Save kube config into vagrant k8s folder
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.kube/config"
    dest: /vagrant/.vagrant/k8s/config
    force: true
