- name: Create kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: Copy kube config
  ansible.builtin.copy:
    src: /vagrant/.vagrant/k8s/config
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    force: true

- name: Determine K8s node status
  command: "kubectl wait --for=condition=Ready nodes/{{ ansible_nodename }} --all --timeout=1s"
  ignore_errors: true
  changed_when: false
  register: k8s_node_status

- name: Join K8s cluster
  become: true
  shell: bash /vagrant/.vagrant/k8s/join.sh
  when: k8s_node_status.rc != 0
