- name: Create kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: Copy kube config
  become: true
  ansible.builtin.copy:
    src: "{{ kubeadmin_config }}"
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    remote_src: true
    force: true

- name: Save kube config to shared folder
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.kube/config"
    dest: /vagrant/tmp/kube-config
    force: true
