- name: Add helm apt key
  become: true
  ansible.builtin.get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /etc/apt/trusted.gpg.d/helm-apt-keyring.asc
    checksum: sha256:d8d0edbdc72338073b7b126be1454c7ebd29bf0da2f64fba87b82d2ae528626d

- name: Add helm apt source
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/helm-apt-keyring.asc] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    update_cache: yes

- name: Install helm binaries
  become: true
  ansible.builtin.apt:
    name: helm
    state: present
